description = "Expression Language Library (JSR245)"
name = "elada_tests"
version = "1.8.8"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["elada_tests.gpr"]
tags = ["web", "expression", "expander", "parser"]
website = "https://gitlab.com/stcarrez/ada-el"
long-description = """

Build and unit tests for elada

"""

[[depends-on]]
elada = "*"
utilada_unit = "^2.8.0"

[configuration]
disabled = true

[[pins]]
elada = { path = '..' }
