description = "Expression Language Library (JSR245) examples"
name = "elada_samples"
version = "1.8.7"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["samples.gpr"]
tags = ["web", "expression", "expander", "parser"]
website = "https://gitlab.com/stcarrez/ada-el"
long-description = """

Build and unit tests for elada

"""

[[depends-on]]
elada = "*"

[configuration]
disabled = true

[[pins]]
elada = { path = '..' }
